sudo: false
language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - 7
before_script:
  - composer self-update
  - composer install
  - php -r \"copy('.env.example', '.env');\"
  - php artisan key:generate
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover